language: php

php:
  - 5.6
  - 7.0

sudo: false

services:
  - mysql

notifications:
  email: false
  
install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS laravel-admin-test;'

before_script: git reset --hard HEAD

script: vendor/bin/phpunit
